(function(root){
'use strict';
const N=typeof module==='object'&&module.exports?require('./nav-core'):root.RutasNav;
function point(c){if(!Array.isArray(c)||c.length<2||!Number.isFinite(c[0])||!Number.isFinite(c[1])||Math.abs(c[0])>180||Math.abs(c[1])>90)throw Error('El servicio devolvió coordenadas inválidas.');return {lat:c[1],lon:c[0]};}
function action(m){const mod=m.modifier||'',right=mod.includes('right'),left=mod.includes('left');if(['roundabout','rotary','roundabout turn'].includes(m.type))return {label:m.exit?'En la rotonda, toma la salida '+m.exit:'Entra en la rotonda',symbol:'⟳'};if(m.type==='exit roundabout'||m.type==='exit rotary')return {label:'Sal de la rotonda',symbol:right?'↱':'↑'};if(mod==='uturn')return {label:'Cambio de sentido',symbol:'↶'};if(m.type==='merge')return {label:right?'Incorpórate por la derecha':left?'Incorpórate por la izquierda':'Incorpórate a la vía',symbol:right?'↱':left?'↰':'↑'};if(m.type==='on ramp'||m.type==='off ramp')return {label:(m.type==='on ramp'?'Toma la incorporación':'Toma la salida')+(right?' a la derecha':left?' a la izquierda':''),symbol:right?'↱':left?'↰':'↑'};return {label:right?'Giro a la derecha':left?'Giro a la izquierda':'Continúa recto',symbol:right?'↱':left?'↰':'↑'};}
function parse(data,origin,target){const selected=data?.routes?.[0];if(data?.code!=='Ok'||!selected)throw Error('No se encontró un acceso por carretera a ese punto.');if(!Array.isArray(selected.legs)||!Number.isFinite(selected.duration)||selected.duration<0)throw Error('El servicio devolvió un acceso incompleto.');const pts=[],turns=[];let distance=0;
for(const leg of selected.legs){if(!Array.isArray(leg.steps))throw Error('Faltan las indicaciones del acceso.');for(const step of leg.steps){const geometry=step.geometry?.coordinates;if(!Array.isArray(geometry)||!geometry.length||!step.maneuver)throw Error('Faltan las indicaciones del acceso.');const first=point(geometry[0]);if(pts.length&&N.distance(pts.at(-1),first)>5)throw Error('El acceso contiene tramos desconectados.');const start=distance;if(!['depart','arrive'].includes(step.maneuver.type))turns.push({d:start,...action(step.maneuver),toRoad:String(step.name||''),roadContext:true});for(const value of geometry){const p=point(value),gap=pts.length?N.distance(pts.at(-1),p):0;if(!pts.length||gap>.01){distance+=gap;pts.push(p);}}}}
if(pts.length<2||distance<1||pts.length>150000)throw Error('No hay un acceso utilizable hasta ese punto.');if(N.distance(pts[0],origin)>100||N.distance(pts.at(-1),target)>60)throw Error('El acceso termina demasiado lejos del punto elegido. Selecciona un punto de la ruta que esté en una calle.');return {pts,turns,duration:selected.duration};}
const api={parse,action};if(typeof module==='object'&&module.exports)module.exports=api;else root.RutasAccessCore=api;
})(typeof globalThis!=='undefined'?globalThis:this);
