/* Routing to the selected GPX start. Only two coordinates leave the device. */
(()=>{
'use strict';
const $=id=>document.getElementById(id),dialog=$('approach-dialog'),start=$('approach-internal');
let controller=null,lastRequest=0;
const recalc=document.createElement('button');recalc.id='access-recalculate';recalc.type='button';recalc.textContent='Recalcular acceso';recalc.hidden=true;$('drive-tools').append(recalc);
const recovery=document.createElement('aside');recovery.id='route-recovery';recovery.hidden=true;recovery.setAttribute('role','alert');recovery.innerHTML='<span aria-hidden="true">↪</span><strong id="route-recovery-head"></strong><small id="route-recovery-text"></small><div class="rec-actions"><button type="button" id="route-recovery-start"></button><button type="button" id="route-recovery-close"></button></div><small id="route-recovery-note"></small>';$('nav-stage').append(recovery);
const R=window.RutasRecoveryCore;
const recoveryStart=$('route-recovery-start'),recoveryClose=$('route-recovery-close'),
      recoveryText=$('route-recovery-text'),recoveryHead=$('route-recovery-head'),recoveryNote=$('route-recovery-note');
let proposal=null,recoveryController=null,dismissedUntil=0;
function showRecovery(state){const c=R.card(state);recovery.dataset.phase=c.phase;
 recoveryHead.textContent=c.head;recoveryText.textContent=c.lead;
 recoveryStart.textContent=c.primary;recoveryClose.textContent=c.secondary;
 recoveryNote.textContent=c.note;recoveryNote.hidden=!c.note;
 recoveryStart.disabled=c.busy;recovery.hidden=false;
 if(window.RutasOverlays)window.RutasOverlays.layout();}
const source=document.createElement('p');source.id='access-source';source.className='hint';source.hidden=true;source.innerHTML='Acceso para coche · <a href="https://routing.openstreetmap.de/about.html" target="_blank" rel="noopener noreferrer">OSRM / FOSSGIS</a> · © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">OpenStreetMap</a> · <a href="https://www.openstreetmap.org/fixthemap" target="_blank" rel="noopener noreferrer">Corregir mapa</a>';$('drive-panel').append(source);
function controls(){const active=RutasMap.get().mode==='access';recalc.hidden=!active;source.hidden=!active;}
function status(text){$('access-status').textContent=text;}
function cancel(){if(controller)controller.abort();controller=null;start.disabled=false;dialog.classList.remove('access-busy');}
function clearRecovery(){proposal=null;dismissedUntil=0;recovery.hidden=true;if(recoveryController)recoveryController.abort();recoveryController=null;recoveryStart.disabled=false;}

async function calculate(origin,target,signal){const coords=[origin,target].map(p=>p.lon.toFixed(6)+','+p.lat.toFixed(6)).join(';');const url='https://routing.openstreetmap.de/routed-car/route/v1/driving/'+coords+'?steps=true&geometries=geojson&overview=full&alternatives=false&radiuses=100;60';const response=await fetch(url,{signal,cache:'no-store'});if(!response.ok)throw Error('El servicio no ha podido calcular el acceso. Vuelve a intentarlo.');return RutasAccessCore.parse(await response.json(),origin,target);}
function position(signal){return new Promise((resolve,reject)=>{if(!navigator.geolocation){reject(Error('Este navegador no permite obtener tu posición.'));return;}let watch=null,settled=false;const finish=(error,value)=>{if(settled)return;settled=true;clearTimeout(timeout);if(watch!==null)navigator.geolocation.clearWatch(watch);signal.removeEventListener('abort',abort);error?reject(error):resolve(value);};const abort=()=>finish(new DOMException('Cancelado','AbortError'));const timeout=setTimeout(()=>finish(Error('No se obtuvo una posición precisa. Activa la ubicación y vuelve a intentarlo.')),20000);signal.addEventListener('abort',abort,{once:true});try{watch=navigator.geolocation.watchPosition(p=>{if(Date.now()-p.timestamp>15000||!Number.isFinite(p.coords.accuracy)||p.coords.accuracy>60){status('Esperando una posición GPS más precisa…');return;}finish(null,{lat:p.coords.latitude,lon:p.coords.longitude});},e=>finish(Error(e.code===1?'Permite el acceso a tu ubicación para calcular el trayecto.':'No se pudo obtener tu posición. Vuelve a intentarlo.')),{enableHighAccuracy:true,maximumAge:0,timeout:15000});}catch{finish(Error('No se pudo iniciar la ubicación.'));}});}
start.onclick=async()=>{if(controller||RutasMap.get().active)return;const current=RutasMap.get(),route=current.route,targetD=current.progress,target=RutasNav.at(route,targetD);if(!route||Roadbook.getRoute().sample)return;const own=new AbortController();controller=own;start.disabled=true;dialog.classList.add('access-busy');status('Buscando tu posición para calcular el acceso…');let timeout;
try{const origin=await position(own.signal);if(own.signal.aborted||RutasMap.get().route!==route)return;if(RutasNav.distance(origin,target)<=60){cancel();dialog.close();$('nav-start').click();return;}if(Date.now()-lastRequest<1500)throw Error('Espera un momento antes de recalcular.');lastRequest=Date.now();status('Calculando un acceso por calles…');timeout=setTimeout(()=>own.abort(),20000);
const access=await calculate(origin,target,own.signal);if(own.signal.aborted||RutasMap.get().route!==route)return;clearTimeout(timeout);window.dispatchEvent(new Event('rutas:access-planned'));controller=null;dialog.close();RutasMap.beginAccess(access);
}catch(e){if(dialog.open){status(e.name==='AbortError'?'La consulta ha tardado demasiado. Puedes reintentar el acceso o volver al mapa.':e.message);}}
finally{clearTimeout(timeout);if(controller===own)controller=null;start.disabled=false;dialog.classList.remove('access-busy');}};
dialog.addEventListener('close',cancel);window.addEventListener('rutas:route',()=>{cancel();clearRecovery();});window.addEventListener('pagehide',()=>{cancel();clearRecovery();});window.addEventListener('rutas:check-route',controls);new MutationObserver(controls).observe($('nav-stop'),{attributes:true,attributeFilter:['disabled']});
recalc.onclick=()=>{RutasMap.stopAccess();$('nav-approach').click();start.click();};controls();
window.addEventListener('rutas:off-route',e=>{if(RutasMap.get().mode==='access'||recoveryController||Date.now()<dismissedUntil)return;proposal=e.detail;showRecovery({gap:proposal.gap,ahead:proposal.ahead});});
window.addEventListener('rutas:on-route',()=>{dismissedUntil=0;proposal=null;recovery.hidden=true;if(recoveryController){recoveryController.abort();recoveryController=null;recoveryStart.disabled=false;}});
recoveryClose.onclick=()=>{if(recoveryController){recoveryController.abort();recoveryController=null;recoveryStart.disabled=false;if(proposal){showRecovery({gap:proposal.gap,ahead:proposal.ahead});return;}}proposal=null;dismissedUntil=Date.now()+30000;recovery.hidden=true;};
recoveryStart.onclick=async()=>{if(!proposal||recoveryController)return;const chosen=proposal,own=new AbortController(),timer=setTimeout(()=>own.abort(),20000);recoveryController=own;showRecovery({phase:'searching'});try{const access=await calculate(chosen.origin,chosen.target,own.signal);if(own.signal.aborted)return;proposal=null;recovery.hidden=true;RutasMap.beginRecovery(access,chosen.targetD,chosen.target);}catch(e){if(own.signal.aborted&&recoveryController!==own)return;showRecovery({phase:'error',message:R.failure(e)});}finally{clearTimeout(timer);if(recoveryController===own)recoveryController=null;recoveryStart.disabled=false;}};
})();
