/* Routing to the selected GPX start. Only two coordinates leave the device. */
(()=>{
'use strict';
const $=id=>document.getElementById(id),dialog=$('approach-dialog'),start=$('approach-internal');
let controller=null,lastRequest=0;
const recalc=document.createElement('button');recalc.id='access-recalculate';recalc.type='button';recalc.textContent='Recalcular acceso';recalc.hidden=true;$('drive-tools').append(recalc);
const source=document.createElement('p');source.id='access-source';source.className='hint';source.hidden=true;source.innerHTML='Acceso para coche · <a href="https://routing.openstreetmap.de/about.html" target="_blank" rel="noopener noreferrer">OSRM / FOSSGIS</a> · © <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener noreferrer">OpenStreetMap</a> · <a href="https://www.openstreetmap.org/fixthemap" target="_blank" rel="noopener noreferrer">Corregir mapa</a>';$('drive-panel').append(source);
function controls(){const active=RutasMap.get().mode==='access';recalc.hidden=!active;source.hidden=!active;}
function status(text){$('access-status').textContent=text;}
function cancel(){if(controller)controller.abort();controller=null;start.disabled=false;dialog.classList.remove('access-busy');}
function position(signal){return new Promise((resolve,reject)=>{if(!navigator.geolocation){reject(Error('Este navegador no permite obtener tu posición.'));return;}let watch=null,settled=false;const finish=(error,value)=>{if(settled)return;settled=true;clearTimeout(timeout);if(watch!==null)navigator.geolocation.clearWatch(watch);signal.removeEventListener('abort',abort);error?reject(error):resolve(value);};const abort=()=>finish(new DOMException('Cancelado','AbortError'));const timeout=setTimeout(()=>finish(Error('No se obtuvo una posición precisa. Activa la ubicación y vuelve a intentarlo.')),20000);signal.addEventListener('abort',abort,{once:true});try{watch=navigator.geolocation.watchPosition(p=>{if(Date.now()-p.timestamp>15000||!Number.isFinite(p.coords.accuracy)||p.coords.accuracy>60){status('Esperando una posición GPS más precisa…');return;}finish(null,{lat:p.coords.latitude,lon:p.coords.longitude});},e=>finish(Error(e.code===1?'Permite el acceso a tu ubicación para calcular el trayecto.':'No se pudo obtener tu posición. Vuelve a intentarlo.')),{enableHighAccuracy:true,maximumAge:0,timeout:15000});}catch{finish(Error('No se pudo iniciar la ubicación.'));}});}
start.onclick=async()=>{if(controller||RutasMap.get().active)return;const current=RutasMap.get(),route=current.route,targetD=current.progress,target=RutasNav.at(route,targetD);if(!route||Roadbook.getRoute().sample)return;const own=new AbortController();controller=own;start.disabled=true;dialog.classList.add('access-busy');status('Buscando tu posición para calcular el acceso…');let timeout;
try{const origin=await position(own.signal);if(own.signal.aborted||RutasMap.get().route!==route)return;if(RutasNav.distance(origin,target)<=60){cancel();dialog.close();$('nav-start').click();return;}if(Date.now()-lastRequest<1500)throw Error('Espera un momento antes de recalcular.');lastRequest=Date.now();status('Calculando un acceso por calles…');timeout=setTimeout(()=>own.abort(),20000);
const coords=[origin,target].map(p=>p.lon.toFixed(6)+','+p.lat.toFixed(6)).join(';');const url='https://routing.openstreetmap.de/routed-car/route/v1/driving/'+coords+'?steps=true&geometries=geojson&overview=full&alternatives=false&radiuses=100;60';const response=await fetch(url,{signal:own.signal,cache:'no-store'});if(!response.ok)throw Error('El servicio no ha podido calcular el acceso. Vuelve a intentarlo.');const data=await response.json();if(own.signal.aborted||RutasMap.get().route!==route)return;const access=RutasAccessCore.parse(data,origin,target);clearTimeout(timeout);window.dispatchEvent(new Event('rutas:access-planned'));controller=null;dialog.close();RutasMap.beginAccess(access);
}catch(e){if(dialog.open){status(e.name==='AbortError'?'La consulta ha tardado demasiado. Puedes reintentar el acceso o volver al mapa.':e.message);}}
finally{clearTimeout(timeout);if(controller===own)controller=null;start.disabled=false;dialog.classList.remove('access-busy');}};
dialog.addEventListener('close',cancel);window.addEventListener('rutas:route',cancel);window.addEventListener('pagehide',cancel);window.addEventListener('rutas:check-route',controls);new MutationObserver(controls).observe($('nav-stop'),{attributes:true,attributeFilter:['disabled']});
recalc.onclick=()=>{RutasMap.stopAccess();$('nav-approach').click();start.click();};controls();
})();
