(()=>{
'use strict';
const $=id=>document.getElementById(id),C=window.RutasNav;
const pendingKey='rutas-approach-v1';let pending=null;
try{const saved=JSON.parse(localStorage.getItem(pendingKey));if(saved&&typeof saved.fingerprint==='string'&&Number.isFinite(saved.progress)&&saved.progress>=0&&Number.isFinite(saved.created)&&Date.now()-saved.created<86400000&&saved.created<=Date.now())pending=saved;}catch{}
const arrival=document.createElement('section');arrival.id='arrival-card';arrival.hidden=true;arrival.innerHTML='<div><strong>Tu ruta te espera</strong><p id="arrival-detail"></p></div><button type="button" class="btn primary" id="arrival-check">Ya he llegado · comprobar GPS</button><button type="button" class="btn sm" id="arrival-dismiss">Descartar acceso</button><p class="hint" id="arrival-feedback" role="status"></p>';$('nav-stage').before(arrival);
function clearPending(){pending=null;arrival.hidden=true;try{localStorage.removeItem(pendingKey);}catch{}}
function arrivalState(){const s=RutasMap.get();if(!pending||!s.route){arrival.hidden=true;return;}if(pending.fingerprint!==C.fingerprint(s.route)||pending.progress>s.route.total||Date.now()-pending.created>=86400000){clearPending();return;}arrival.hidden=s.active;$('arrival-detail').textContent=pending.progress>50?'Vuelve al punto elegido, a '+(pending.progress/1000).toLocaleString('es-ES',{maximumFractionDigits:2})+' km del comienzo.':'Vuelve aquí al llegar al inicio del recorrido.';$('arrival-check').disabled=s.active;}
$('arrival-dismiss').onclick=clearPending;
$('arrival-check').onclick=()=>{if(!pending||RutasMap.get().active)return;RutasMap.seek(pending.progress);$('arrival-feedback').textContent='Comprobando tu posición…';$('nav-start').click();};

const button=document.createElement('button');button.id='nav-approach';button.type='button';button.className='btn';button.textContent='Llegar al inicio';$('nav-fit').parentElement.append(button);
const dialog=document.createElement('dialog');dialog.id='approach-dialog';dialog.setAttribute('aria-labelledby','approach-title');dialog.setAttribute('aria-describedby','approach-description');
dialog.innerHTML='<span class="approach-symbol" aria-hidden="true">↗</span><h2 id="approach-title">Llegar al inicio</h2><p id="approach-description"></p><a id="approach-open" class="btn primary" target="_blank" rel="noopener noreferrer">Llevarme con Google Maps ↗</a><p class="hint">Google Maps calcula el acceso en coche. Al llegar, vuelve a Rutas y pulsa Iniciar navegación para seguir tu GPX. Este acceso no tiene en cuenta las medidas de tu vehículo.</p><p class="hint">Se abre Google Maps con el punto de destino; no se comparte el GPX completo.</p><div class="btnrow"><button id="approach-choose" class="btn" type="button">Elegir otra pasada</button><button id="approach-close" class="btn" type="button" autofocus>Volver al mapa</button></div>';
document.body.append(dialog);
function refresh(){const s=RutasMap.get();button.disabled=Roadbook.getRoute().sample||s.active;button.textContent=s.progress>50?'Llegar al punto seleccionado':'Llegar al inicio';arrivalState();}
function open(distance=null){const s=RutasMap.get();if(!s.route||Roadbook.getRoute().sample)return;const p=C.at(s.route,s.progress),selected=s.progress>50;$('approach-title').textContent=selected?'Llegar al punto seleccionado':'Llegar al inicio de la ruta';$('approach-description').textContent=distance!==null?'Estás a '+(distance>=1000?(distance/1000).toLocaleString('es-ES',{maximumFractionDigits:1})+' km':Math.round(distance)+' m')+' en línea recta. El seguimiento del GPX comenzará cuando estés cerca del punto seleccionado.':selected?'Te llevamos al punto que has elegido para continuar el recorrido.':'Te llevamos hasta el primer punto del recorrido desde tu ubicación actual.';
const url=new URL('https://www.google.com/maps/dir/');url.searchParams.set('api','1');url.searchParams.set('destination',p.lat.toFixed(6)+','+p.lon.toFixed(6));url.searchParams.set('travelmode','driving');url.searchParams.set('dir_action','navigate');$('approach-open').href=url.href;if(!dialog.open)dialog.showModal();}
button.onclick=()=>open();$('approach-close').onclick=()=>dialog.close();$('approach-choose').onclick=()=>{dialog.close();const section=document.querySelector('.resume-section').closest('details');section.open=true;section.scrollIntoView({block:'center'});$('nav-locate-pass').focus();};$('approach-open').onclick=()=>{const s=RutasMap.get();pending={fingerprint:C.fingerprint(s.route),progress:s.progress,created:Date.now()};try{localStorage.setItem(pendingKey,JSON.stringify(pending));}catch{}$('arrival-feedback').textContent='';dialog.close();arrivalState();$('nav-message').textContent='Cuando llegues al punto seleccionado, vuelve aquí y pulsa Iniciar navegación.';};
window.addEventListener('rutas:approach',e=>{$('arrival-feedback').textContent='Todavía estás lejos del punto elegido.';open(e.detail.distance);});window.addEventListener('rutas:check-route',()=>{dialog.close();refresh();});window.addEventListener('rutas:progress',()=>{const s=RutasMap.get();if(pending&&s.active&&s.location&&C.distance({lat:s.location.lat,lon:s.location.lng},C.at(s.route,pending.progress))<=100)clearPending();refresh();});document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});new MutationObserver(refresh).observe($('nav-stop'),{attributes:true,attributeFilter:['disabled']});refresh();
})();
