/* Compact route-load review. It only combines results already calculated locally. */
(()=>{
'use strict';
const C=window.RutasNav,anchor=document.getElementById('street-match');
if(!anchor)return;
const card=document.createElement('details');card.id='route-audit';card.open=true;card.innerHTML='<summary><span class="audit-shield" aria-hidden="true">✓</span><span><strong>Revisión automática</strong><small id="audit-headline">Preparando el recorrido…</small></span><b id="audit-badge">Analizando</b></summary><div class="audit-body"><div class="audit-row" data-kind="route"><i>1</i><span><b>Archivo y continuidad</b><small id="audit-route">Leyendo el GPX…</small></span></div><div class="audit-row" data-kind="streets"><i>2</i><span><b>Recorrido por calles</b><small id="audit-streets">Esperando el reconocimiento…</small></span></div><div class="audit-row" data-kind="rules"><i>3</i><span><b>Sentidos y restricciones</b><small id="audit-rules">Esperando los datos viales…</small></span></div><button type="button" class="btn sm" id="audit-open-warnings" hidden>Ver avisos en el mapa</button></div>';
anchor.after(card);
const $=id=>document.getElementById(id);let street={state:'idle'},safety=null,roadState='idle';
const metres=m=>m<1000?Math.round(m)+' m':(m/1000).toFixed(2).replace('.',',')+' km';
function mark(kind,state){const row=card.querySelector('[data-kind="'+kind+'"]');row.dataset.state=state;row.querySelector('i').textContent=state==='ok'?'✓':state==='warn'?'!':state==='error'?'×':'…';}
function routeReview(){const data=Roadbook.getRoute(),state=RutasMap.get();if(!state.route||data.sample){$('audit-route').textContent='Carga un GPX real para revisarlo.';mark('route','idle');return;}const parts=data.parts||[data.pts],turns=C.turns(state.route).length,stops=C.stops(state.route).length;let jumps=0;for(let i=1;i<parts.length;i++)if(parts[i-1]?.length&&parts[i]?.length&&C.distance(parts[i-1].at(-1),parts[i][0])>80)jumps++;$('audit-route').textContent=metres(state.route.total)+' · '+parts.length+(parts.length===1?' segmento':' segmentos')+' · '+turns+' giros · '+stops+' paradas'+(jumps?' · '+jumps+' cortes entre segmentos':' · continuidad correcta');mark('route',jumps?'warn':'ok');}
function readStreet(){const s=window.RutasStreetMatch?.get();if(s)street={...street,...s};}
function paint(){routeReview();readStreet();const text=$('audit-streets');if(street.state==='loading'){text.textContent='Buscando carreteras próximas a los puntos del GPX…';mark('streets','loading');}else if(street.state==='ready'){text.textContent=(street.coverage??'—')+' % de coincidencia · navegación preparada sobre calles'+(street.gaps?' · '+street.gaps+' cortes pendientes':' · sin cortes');mark('streets',street.gaps?'warn':'ok');}else if(street.state==='warn'){text.textContent='El trazado vial necesita revisión; se conserva el GPX original.';mark('streets','warn');}else if(street.state==='error'){text.textContent='No se pudieron reconocer las calles; se conserva el GPX original.';mark('streets','error');}else{text.textContent='Esperando el reconocimiento de calles…';mark('streets','idle');}
 const current=window.RutasChecks?.getSummary?.();if(current)safety=current;const rules=$('audit-rules'),button=$('audit-open-warnings');if(!safety){if(street.state==='warn'||street.state==='error'||roadState==='error'){rules.textContent='No se pudo completar la comprobación vial; utiliza Actualizar datos viales para reintentarlo.';mark('rules',street.state==='error'||roadState==='error'?'error':'warn');}else{rules.textContent=street.state==='ready'?'Consultando sentidos y límites conocidos…':'Esperando a que termine el trazado vial…';mark('rules','loading');}button.hidden=true;}else{const bits=[];if(safety.opposed)bits.push(safety.opposed+' posibles contramanos');if(safety.vehicle)bits.push(safety.vehicle+' restricciones del vehículo');if(safety.doubtful)bits.push(safety.doubtful+' puntos dudosos');rules.textContent=bits.length?bits.join(' · ')+' · '+safety.coverage+' % comprobado':'Sin conflictos detectados · '+safety.coverage+' % comprobado';mark('rules',safety.live?'warn':'ok');button.hidden=!safety.live;}
 const bad=card.querySelectorAll('.audit-row[data-state="warn"],.audit-row[data-state="error"]').length,pending=card.querySelectorAll('.audit-row[data-state="idle"],.audit-row[data-state="loading"]').length;$('audit-badge').textContent=pending?'Analizando':bad?'Revisar':'Preparada';card.dataset.state=pending?'loading':bad?'warn':'ok';$('audit-headline').textContent=pending?'Comprobando calles, continuidad y restricciones…':bad?(bad===1?'Hay 1 apartado que conviene revisar':'Hay '+bad+' apartados que conviene revisar'):'Ruta preparada para navegar';if(!pending&&bad)card.open=true;}
function reset(){street={state:'idle'};safety=null;roadState='idle';paint();}
window.addEventListener('rutas:check-route',reset);window.addEventListener('rutas:navigation-path',()=>{routeReview();paint();});window.addEventListener('rutas:street-state',e=>{street={...street,...e.detail};paint();});window.addEventListener('rutas:street-path',e=>{street={...street,...e.detail};paint();});window.addEventListener('rutas:road-state',e=>{roadState=e.detail?.state||'idle';if(roadState==='ready')safety=window.RutasChecks?.getSummary?.()||null;paint();});window.addEventListener('rutas:roads',()=>{safety=window.RutasChecks?.getSummary?.()||null;paint();});
$('audit-open-warnings').onclick=()=>{const review=document.querySelector('.road-review');review?.scrollIntoView({behavior:'smooth',block:'start'});};
reset();
})();
