/* Ajustes de cabina: alta visibilidad y comprobacion real de la salida de voz del coche. */
(()=>{
'use strict';
const KEY='rutas-alta-visibilidad',AUDIO='rutas-audio-coche-prueba';let tested=0,statusEl;
try{tested=Number(localStorage.getItem(AUDIO))||0;}catch{}
function high(on){document.documentElement.classList.toggle('alta-visibilidad',!!on);try{localStorage.setItem(KEY,on?'1':'0');}catch{}return !!on;}
let saved=false;try{saved=localStorage.getItem(KEY)==='1';}catch{}high(saved);
function apple(){return /iPhone|iPad|iPod/i.test(navigator.userAgent);}
async function outputs(){try{if(!navigator.mediaDevices?.enumerateDevices)return [];return (await navigator.mediaDevices.enumerateDevices()).filter(d=>d.kind==='audiooutput');}catch{return [];}}
function message(list){if(apple())return 'En iPhone, conecta el coche desde Ajustes o el Centro de control y elige su salida de audio. Después vuelve aquí y prueba la voz.';if(list.length)return 'El navegador detecta '+list.length+(list.length===1?' salida de audio.':' salidas de audio.')+' La voz usará la salida elegida en el sistema.';return 'Conecta el coche en los ajustes Bluetooth del teléfono. La voz de Rutas usa la salida de audio elegida por el sistema.';}
async function refresh(){const list=await outputs();if(statusEl)statusEl.textContent=message(list)+(tested?' Última prueba realizada: '+new Date(tested).toLocaleString('es-ES',{dateStyle:'short',timeStyle:'short'})+'.':'');window.dispatchEvent(new CustomEvent('rutas:car-audio',{detail:state()}));}
function test(){if(!window.speechSynthesis){if(statusEl)statusEl.textContent='Este navegador no puede reproducir indicaciones por voz.';return false;}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance('Prueba de audio de Rutas. Si me oyes en el coche, el Bluetooth está preparado.');u.lang='es-ES';speechSynthesis.speak(u);tested=Date.now();try{localStorage.setItem(AUDIO,String(tested));}catch{}refresh();return true;}
function state(){return {tested,ready:tested>0&&Date.now()-tested<24*3600000,system:true,direct:false,apple:apple()};}
function mount(){const host=document.querySelector('.route-settings-body');if(!host)return setTimeout(mount,80);const card=document.createElement('section');card.className='cabina-settings';card.innerHTML='<div class="cabina-setting"><div><small>VISIBILIDAD</small><h3>Modo de alta visibilidad</h3><p class="hint">Aumenta textos, contraste y mandos durante la navegación.</p></div><button type="button" class="btn sm cabina-high" aria-pressed="false"></button></div><div class="cabina-setting"><div><small>AUDIO DEL COCHE</small><h3>Bluetooth y voz</h3><p class="hint cabina-audio" role="status"></p></div><button type="button" class="btn sm cabina-test">Probar voz</button></div>';host.append(card);const b=card.querySelector('.cabina-high');statusEl=card.querySelector('.cabina-audio');const paint=()=>{const on=document.documentElement.classList.contains('alta-visibilidad');b.textContent=on?'Alta visibilidad activada':'Activar alta visibilidad';b.setAttribute('aria-pressed',String(on));};b.onclick=()=>{high(!document.documentElement.classList.contains('alta-visibilidad'));paint();};card.querySelector('.cabina-test').onclick=test;paint();refresh();navigator.mediaDevices?.addEventListener?.('devicechange',refresh);}
addEventListener('load',mount,{once:true});window.RutasCoche={state,test,refresh,high};
})();
