(()=>{
'use strict';
const body=document.querySelector('.nav-shell>.panel-bd');
if(!body)return;
const card=document.createElement('section');
card.id='gps-setup';
card.className='gps-setup';
card.setAttribute('aria-labelledby','gps-setup-title');
card.innerHTML='<div class="gps-setup-icon" aria-hidden="true"><span></span></div><div class="gps-setup-copy"><small>PREPARAR EL IPHONE</small><h3 id="gps-setup-title">Activa tu ubicación</h3><p id="gps-setup-status" role="status" aria-live="polite">Permite el GPS una vez para ver dónde estás y poder iniciar la navegación sin interrupciones.</p><div class="gps-setup-actions"><button type="button" class="btn primary" id="gps-setup-button">Activar ubicación</button><span id="gps-setup-privacy">Tus coordenadas no se guardan.</span></div><div id="gps-setup-help" hidden><b>Si Safari ha bloqueado el permiso</b><p>En esta web, abre el menú de página, entra en Ajustes del sitio web y cambia Ubicación a Permitir. También puedes revisar Ajustes del iPhone → Privacidad y seguridad → Localización y activar Ubicación precisa para Safari.</p></div></div>';
const hero=body.querySelector('.route-overview');
(hero||body.firstElementChild).after(card);
const button=card.querySelector('#gps-setup-button'),status=card.querySelector('#gps-setup-status'),help=card.querySelector('#gps-setup-help');
function state(name,title,text,label){card.dataset.state=name;card.querySelector('h3').textContent=title;status.textContent=text;button.textContent=label;button.disabled=name==='loading';help.hidden=name!=='denied';}
function success(pos){const accuracy=Number(pos.coords.accuracy),good=Number.isFinite(accuracy)&&accuracy<=40;window.RutasMap?.previewPosition(pos);state(good?'ready':'weak',good?'Ubicación preparada':'Ubicación permitida',Number.isFinite(accuracy)?(good?'Señal GPS lista · precisión de '+Math.round(accuracy)+' m':'Señal débil · precisión de '+Math.round(accuracy)+' m. Sal al exterior y comprueba de nuevo.'):'El permiso está activo.','Comprobar señal');window.dispatchEvent(new CustomEvent('rutas:gps-ready',{detail:{accuracy}}));}
function failure(error){if(error&&error.code===1){state('denied','Ubicación bloqueada','Safari no tiene permiso para usar tu ubicación. Revisa los ajustes indicados y vuelve a intentarlo.','Reintentar');return;}state('error','No encuentro la señal GPS',error&&error.code===3?'La comprobación ha tardado demasiado. Sal al exterior y vuelve a intentarlo.':'Comprueba que la Localización del iPhone esté activa y vuelve a intentarlo.','Reintentar');}
button.addEventListener('click',()=>{if(!navigator.geolocation){state('error','GPS no disponible','Este navegador no ofrece acceso a la ubicación. Abre la app con Safari en el iPhone.','Volver a comprobar');return;}state('loading','Buscando tu ubicación','Mantén esta pantalla abierta mientras el iPhone obtiene una posición precisa…','Buscando GPS…');try{navigator.geolocation.getCurrentPosition(success,failure,{enableHighAccuracy:true,maximumAge:0,timeout:20000});}catch(error){failure(error);}});
if(!navigator.geolocation){state('error','GPS no disponible','Abre la app con Safari para poder usar la ubicación del iPhone.','Volver a comprobar');}
else if(navigator.permissions&&navigator.permissions.query){navigator.permissions.query({name:'geolocation'}).then(permission=>{if(permission.state==='granted')state('allowed','Ubicación permitida','El permiso ya está activo. Comprueba la señal antes de salir.','Comprobar señal');else if(permission.state==='denied')state('denied','Ubicación bloqueada','Safari no tiene permiso para usar tu ubicación. Revisa los ajustes indicados y vuelve a intentarlo.','Reintentar');permission.addEventListener?.('change',()=>{if(permission.state==='granted')state('allowed','Ubicación permitida','El permiso ya está activo. Comprueba la señal antes de salir.','Comprobar señal');else if(permission.state==='denied')state('denied','Ubicación bloqueada','Safari no tiene permiso para usar tu ubicación. Revisa los ajustes indicados y vuelve a intentarlo.','Reintentar');});}).catch(()=>{});}
})();
