/* Private route library. IndexedDB stays in this browser; no network requests. */
(()=>{
'use strict';
const $=id=>document.getElementById(id);
const launcher=document.createElement('button');launcher.id='library-open';launcher.type='button';launcher.className='btn';launcher.textContent='Mis rutas';$('nav-file').parentElement.after(launcher);$('nav-forget').title='Borra la última ruta recuperada al abrir la app. Las copias de Mis rutas se eliminan desde la biblioteca.';
const dialog=document.createElement('dialog');dialog.id='route-library';dialog.setAttribute('aria-labelledby','library-title');dialog.innerHTML='<header><div><span class="library-eyebrow">TU BIBLIOTECA PRIVADA</span><h2 id="library-title">Mis rutas</h2></div><button type="button" id="library-close" class="btn sm" aria-label="Cerrar biblioteca">Cerrar</button></header><p class="hint">Guardadas solo en este navegador. No se publican ni se envían a un servidor. Conserva tus archivos GPX como copia.</p><button type="button" id="library-save" class="btn primary">Guardar recorrido actual</button><label class="library-search">Buscar una ruta<input type="search" id="library-search" placeholder="Nombre de la ruta" autocomplete="off"></label><p id="library-status" role="status"></p><button type="button" class="btn sm" id="library-undo" hidden>Deshacer eliminación</button><div id="library-list"></div>';document.body.append(dialog);
let dbPromise=null,records=[],busy=false,removed=null,queryVersion=0;
function db(){if(!dbPromise)dbPromise=new Promise((resolve,reject)=>{const request=indexedDB.open('rutas-library',1);request.onupgradeneeded=()=>request.result.createObjectStore('routes',{keyPath:'id'});request.onsuccess=()=>{const connection=request.result;connection.onversionchange=()=>{connection.close();dbPromise=null;};resolve(connection);};request.onerror=()=>{dbPromise=null;reject(request.error);};request.onblocked=()=>{dbPromise=null;reject(Error('blocked'));};});return dbPromise;}
async function operation(mode,action){const connection=await db();return new Promise((resolve,reject)=>{const tx=connection.transaction('routes',mode),request=action(tx.objectStore('routes'));tx.oncomplete=()=>resolve(request.result);tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error);});}
function notice(text){$('library-status').textContent=text;}
function controls(){const active=RutasMap.get().active;launcher.disabled=active;$('library-save').disabled=busy||active||Roadbook.getRoute().sample;$('library-undo').disabled=busy;dialog.querySelectorAll('#library-list button').forEach(b=>b.disabled=busy||active);}
function valid(record){return Array.isArray(record.tracks)&&record.tracks.length>0&&record.tracks.every(t=>Array.isArray(t.pts)&&t.pts.length>1&&t.pts.every(p=>p&&Number.isFinite(p.lat)&&Number.isFinite(p.lon)&&Math.abs(p.lat)<=90&&Math.abs(p.lon)<=180));}
function render(){const list=$('library-list');list.replaceChildren();const query=$('library-search').value.trim().toLocaleLowerCase('es');const rows=records.filter(r=>r.title.toLocaleLowerCase('es').includes(query)).sort((a,b)=>b.updated-a.updated);if(!rows.length){const empty=document.createElement('p');empty.className='library-empty';empty.textContent=query?'No hay rutas con ese nombre.': 'Tu biblioteca está vacía. Carga un GPX y pulsa Guardar recorrido actual.';list.append(empty);}
for(const record of rows){const card=document.createElement('article');card.className='library-route';const title=document.createElement('h3');title.textContent=record.title;const meta=document.createElement('p');meta.className='hint';meta.textContent=record.km.toLocaleString('es-ES',{maximumFractionDigits:2})+' km · '+record.tracks.length+' segmento'+(record.tracks.length===1?'':'s')+' · '+new Date(record.updated).toLocaleDateString('es-ES');const actions=document.createElement('div');actions.className='btnrow';const use=button('Abrir ruta',()=>{if(RutasMap.get().active)return;if(!valid(record)){notice('No se pudo leer esta ruta. Vuelve a cargar su GPX original.');return;}Roadbook.restoreRoute(structuredClone(record.tracks),record.title+'.gpx');if(record.selected>0&&record.selected<record.tracks.length)Roadbook.selectTrack(record.selected);dialog.close();$('nav-message').textContent='Ruta abierta desde tu biblioteca. Revisa el punto de inicio antes de navegar.';});use.classList.add('primary');
const rename=button('Renombrar',()=>{form.hidden=!form.hidden;if(!form.hidden)input.focus();});const remove=button('Eliminar',()=>write(async()=>{await operation('readwrite',s=>s.delete(record.id));removed=record;$('library-undo').hidden=false;await load();notice('Ruta eliminada de la biblioteca. Puedes deshacerlo.');}));remove.setAttribute('aria-label','Eliminar '+record.title+' de la biblioteca');actions.append(use,rename,remove);
const form=document.createElement('form');form.className='library-rename';form.hidden=true;const input=document.createElement('input');input.type='text';input.value=record.title;input.maxLength=80;input.required=true;input.setAttribute('aria-label','Nuevo nombre de la ruta');const submit=document.createElement('button');submit.type='submit';submit.className='btn';submit.textContent='Guardar nombre';form.append(input,submit);form.onsubmit=e=>{e.preventDefault();const name=input.value.trim();if(!name){input.focus();return;}write(async()=>{await operation('readwrite',s=>s.put({...record,title:name,updated:Date.now()}));await load();notice('Nombre actualizado.');});};card.append(title,meta,actions,form);list.append(card);}controls();}
function button(text,click){const b=document.createElement('button');b.type='button';b.className='btn sm';b.textContent=text;b.onclick=click;return b;}
async function load(){const version=++queryVersion;const values=await operation('readonly',s=>s.getAll());if(version!==queryVersion)return;records=values.filter(r=>r&&valid(r)&&typeof r.title==='string'&&Number.isFinite(r.km)&&Number.isFinite(r.updated));render();}
async function write(action){if(busy)return;busy=true;controls();try{await action();}catch{notice('No se pudo guardar el cambio. Comprueba el espacio disponible y los permisos de almacenamiento del navegador.');}finally{busy=false;controls();}}
launcher.onclick=async()=>{if(RutasMap.get().active)return;dialog.showModal();notice('Cargando tus rutas…');controls();try{await load();notice('');}catch{notice('No se puede abrir el almacenamiento de este navegador. Tu recorrido actual sigue disponible.');}};
$('library-close').onclick=()=>dialog.close();$('library-search').oninput=render;
$('library-save').onclick=()=>write(async()=>{const data=Roadbook.getRoute();if(data.sample||RutasMap.get().active)return;const tracks=structuredClone(data.tracks);tracks[data.selected].pts=structuredClone(data.pts);const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(tracks.map(t=>t.pts))));const id=Array.from(new Uint8Array(bytes),b=>b.toString(16).padStart(2,'0')).join('');const existing=await operation('readonly',s=>s.get(id));const record={id,title:existing?.title||String(data.name||'Mi ruta').replace(/\.gpx$/i,'').slice(0,80),tracks,selected:data.selected,km:RutasNav.prepare(data.pts).total/1000,updated:Date.now()};await operation('readwrite',s=>s.put(record));if(removed?.id===id){removed=null;$('library-undo').hidden=true;}await load();notice(existing?'Ruta actualizada sin duplicarla.':'Ruta guardada en este dispositivo.');});
$('library-undo').onclick=()=>write(async()=>{if(!removed)return;await operation('readwrite',s=>s.put(removed));removed=null;$('library-undo').hidden=true;await load();notice('Ruta recuperada.');});
window.addEventListener('rutas:check-route',controls);new MutationObserver(controls).observe($('nav-stop'),{attributes:true,attributeFilter:['disabled']});controls();
})();
