(function(){
'use strict';
const $=id=>document.getElementById(id),C=window.RutasNav;
let arrowLayer,completed,turns=[],announced=-1,lastPosition=null;
let map,layer,preview,position,accuracy,remaining,route,progress=0,explore=0,watch=null,lock=null,session=0,playing=null,follow=true,lastFix=null,lastVoice=0,lastAlert='',routeRef;
const metres=m=>m<1000?Math.round(m)+' m':(m/1000).toFixed(2).replace('.',',')+' km';
function message(text,warn=false){$('nav-message').textContent=text;$('nav-message').classList.toggle('warn',warn);}
function speak(text){if(!$('nav-voice').checked||!window.speechSynthesis)return;if(text===lastAlert&&Date.now()-lastVoice<30000)return;lastVoice=Date.now();lastAlert=text;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='es-ES';window.speechSynthesis.speak(u);}
function ll(p){return [p.lat,p.lon];}
function init(){if(map)return true;if(!window.L){message('No se pudo cargar el mapa. Recarga la página.',true);return false;}map=L.map('nav-map').setView([40.4,-3.7],6);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).on('tileerror',()=>message('No se pudo cargar parte del mapa. Comprueba tu conexión.',true)).addTo(map);L.control.scale({imperial:false}).addTo(map);map.on('dragstart',()=>{follow=false;});map.on('zoomend',()=>{if(route&&layer)drawArrows();});return true;}
function metrics(d){$('nav-done').textContent=metres(d);$('nav-left').textContent=metres(Math.max(0,route.total-d));}
function street(d){const p=C.at(route,d),q=C.at(route,Math.min(route.total,d+30)),h=C.heading(d>=route.total?C.at(route,Math.max(0,d-30)):p,q);$('nav-street').href='https://www.google.com/maps/@?api=1&map_action=pano&viewpoint='+encodeURIComponent(p.lat.toFixed(6)+','+p.lon.toFixed(6))+'&heading='+h.toFixed(0);}
function showPreview(d,pan=false){if(!route)return;explore=Math.max(0,Math.min(route.total,d));const p=C.at(route,explore);preview.setLatLng(ll(p));$('nav-progress').value=route.total?Math.round(explore/route.total*1000):0;$('nav-preview-distance').textContent=metres(explore);street(explore);paint(explore);if(watch===null)metrics(explore);if(pan)map.panTo(ll(p));}
function pause(){if(playing)clearInterval(playing);playing=null;$('nav-play').textContent='Reproducir';}
function controls(active){$('nav-focus-stop').hidden=!active;$('nav-start').disabled=active;$('nav-stop').disabled=!active;['nav-progress','nav-back','nav-next','nav-play','nav-reset'].forEach(id=>$(id).disabled=active);$('nav-mode').textContent=active?'GPS activo':'Vista previa';}
function stop(quiet=false){session++;if(watch!==null)navigator.geolocation.clearWatch(watch);watch=null;lastFix=null;lastPosition=null;if(lock){lock.release().catch(()=>{});lock=null;}controls(false);if(window.speechSynthesis)window.speechSynthesis.cancel();if(!quiet)message('GPS detenido. Puedes explorar la ruta o continuar desde el punto seleccionado.');}
function sync(){if(!init())return;const data=window.Roadbook.getRoute();if(data.pts===routeRef){map.invalidateSize();return;}stop(true);pause();routeRef=data.pts;route=C.prepare(data.pts);progress=0;explore=0;if(layer)map.removeLayer(layer);if(position){map.removeLayer(position);position=null;}if(accuracy){map.removeLayer(accuracy);accuracy=null;}layer=L.featureGroup().addTo(map);const coords=data.pts.map(ll);L.polyline(coords,{color:'#ffffff',weight:9,opacity:.9}).addTo(layer);L.polyline(coords,{color:'#6e8090',weight:5,opacity:.85}).addTo(layer);completed=L.polyline([],{color:'#248660',weight:5,opacity:.9}).addTo(layer);remaining=L.polyline([],{color:'#176dcc',weight:6}).addTo(layer);for(const [p,label,cl] of [[coords[0],'A',''],[coords.at(-1),'B','end']])L.marker(p,{icon:L.divIcon({className:'nav-pin '+cl,html:label,iconSize:[28,28]})}).addTo(layer);turns=C.turns(route);announced=-1;drawTurns();drawArrows();preview=L.circleMarker(coords[0],{radius:8,color:'#fff',weight:3,fillColor:'#176dcc',fillOpacity:1}).addTo(layer);map.fitBounds(layer.getBounds(),{padding:[25,25],maxZoom:17});$('nav-name').textContent=(data.sample?'Ejemplo ficticio · carga tu GPX para navegar':'Archivo: '+data.name)+' · '+metres(route.total)+' · '+data.pts.length.toLocaleString('es-ES')+' puntos';$('nav-track').replaceChildren(...data.tracks.map((t,i)=>{const o=document.createElement('option');o.value=i;o.textContent=t.name;o.selected=i===data.selected;return o;}));$('nav-start').disabled=data.sample||route.total<1;message(data.sample?'Vista previa de ejemplo. Carga un GPX real para iniciar el GPS.':'Ruta preparada. Explora las calles o inicia el GPS.');$('nav-speed').textContent='—';$('nav-accuracy').textContent='—';showPreview(0);saveLocal(data);}
function update(pos,token){if(token!==session||watch===null)return;const c=pos.coords,p={lat:c.latitude,lon:c.longitude};$('nav-accuracy').textContent=Math.round(c.accuracy)+' m';$('nav-speed').textContent=c.speed!==null&&c.speed>=0?Math.round(c.speed*3.6)+' km/h':'—';if(!position){position=L.circleMarker(ll(p),{radius:9,color:'#fff',weight:3,fillColor:'#006dff',fillOpacity:1}).addTo(map);accuracy=L.circle(ll(p),{radius:c.accuracy,color:'#006dff',weight:1,fillOpacity:.08}).addTo(map);}position.setLatLng(ll(p));accuracy.setLatLng(ll(p)).setRadius(c.accuracy);if(follow)map.setView(ll(p),Math.max(map.getZoom(),17),{animate:false});if(c.accuracy>60){message('Señal GPS imprecisa. Esperando una posición más fiable.',true);return;}const elapsed=lastFix?(pos.timestamp-lastFix)/1000:0;const allowance=Math.min(350,Math.max(250,elapsed*30));const travelled=lastPosition?C.distance(lastPosition,p):0;const expected=progress+Math.min(travelled,allowance);const m=C.match(route,p,progress,allowance,expected);lastPosition=p;lastFix=pos.timestamp;if(!m||m.error>Math.max(35,c.accuracy*1.5)){message('Fuera del tramo previsto. Vuelve a la línea; si has cambiado de pasada, para y ajusta el punto de inicio.',true);speak('Te has alejado del recorrido. Comprueba el mapa.');return;}progress=Math.max(progress,m.d);showPreview(progress);metrics(progress);const turn=turns.find(t=>t.d>progress+8);if(turn&&turn.d-progress<70&&announced!==turn.d){announced=turn.d;speak("En "+metres(turn.d-progress)+", "+turn.label.toLowerCase()+", según el recorrido.");}if(route.total-progress<15&&C.distance(p,route.pts.at(-1))<25){stop(true);$('nav-start').disabled=false;message('Has llegado al final del recorrido.');speak('Has llegado al final del recorrido.');return;}message('En ruta · sigue el tramo azul · quedan '+metres(route.total-progress));}
async function acquire(token){if(!navigator.wakeLock||document.hidden)return;try{const l=await navigator.wakeLock.request('screen');if(token===session&&watch!==null)lock=l;else await l.release();}catch{}}
$('nav-start').onclick=()=>{if(!route||watch!==null||window.Roadbook.getRoute().sample)return;if(!navigator.geolocation){message('Este navegador no permite acceder al GPS.',true);return;}pause();progress=explore;follow=true;const token=++session;controls(true);message('Buscando tu posición…');try{watch=navigator.geolocation.watchPosition(p=>update(p,token),e=>{if(token!==session)return;stop(true);message(e.code===1?'Permiso de ubicación denegado. Actívalo en los ajustes del navegador.':'No se pudo obtener el GPS. Puedes volver a intentarlo.',true);},{enableHighAccuracy:true,maximumAge:0,timeout:20000});acquire(token);}catch{stop(true);message('No se pudo iniciar el GPS.',true);}};

function paint(d){if(!completed)return;completed.setLatLngs(C.section(route,0,d).map(ll));remaining.setLatLngs(C.section(route,d,Math.min(route.total,d+200)).map(ll));const t=turns.find(t=>t.d>d+8);$('nav-turn-icon').textContent=d>=route.total-5?'✓':t?t.symbol:'↑';$('nav-turn-text').textContent=d>=route.total-5?'Final del recorrido':t?t.label:'Sigue hasta el final';$('nav-turn-distance').textContent=(t?'En '+metres(t.d-d):metres(route.total-d)+' restantes')+' · según el GPX';}
function drawArrows(){if(arrowLayer)layer.removeLayer(arrowLayer);arrowLayer=L.featureGroup().addTo(layer);const scale=156543.03*Math.cos(route.pts[0].lat*Math.PI/180)/Math.pow(2,map.getZoom()),step=Math.max(60,scale*70,route.total/200),seen=new Set();for(let d=step;d<route.total;d+=step){const p=C.at(route,d),pixel=map.latLngToLayerPoint(ll(p)),key=Math.round(pixel.x/40)+':'+Math.round(pixel.y/40);if(seen.has(key))continue;seen.add(key);const h=C.heading(C.at(route,d-15),C.at(route,Math.min(route.total,d+15)));L.marker(ll(p),{interactive:false,icon:L.divIcon({className:'route-arrow',html:'<span style="transform:rotate('+(h-90)+'deg)">➤</span>',iconSize:[16,16],iconAnchor:[8,8]})}).addTo(arrowLayer);}}

function drawTurns(){const list=$('nav-turns');list.replaceChildren();$('nav-turn-count').textContent='('+turns.length+')';for(const t of turns){const li=document.createElement('li'),b=document.createElement('button');b.type='button';b.textContent=metres(t.d)+' · '+t.symbol+' '+t.label;b.onclick=()=>{if(watch!==null){message('Para el GPS antes de cambiar el punto del recorrido.',true);return;}pause();showPreview(Math.max(0,t.d-25),true);map.setZoom(18);};li.append(b);list.append(li);}}
function saveLocal(data){if(data.sample)return;try{localStorage.setItem('rutas-route',JSON.stringify({name:data.name,tracks:data.tracks,selected:data.selected}));$('nav-local').textContent='Ruta guardada solo en este navegador. No se publica ni se sube a un servidor.';}catch{$('nav-local').textContent='No se pudo guardar la ruta en este navegador. Puedes usarla, pero tendrás que cargarla de nuevo al volver.';}}
function restoreLocal(){try{const data=JSON.parse(localStorage.getItem('rutas-route'));if(!data||!Array.isArray(data.tracks)||!data.tracks.length)return;const valid=data.tracks.every(t=>Array.isArray(t.pts)&&t.pts.length>1&&t.pts.every(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon)&&Math.abs(p.lat)<=90&&Math.abs(p.lon)<=180));if(!valid)return;window.Roadbook.restoreRoute(data.tracks,String(data.name||'Ruta guardada'));if(Number.isInteger(data.selected)&&data.selected>0&&data.selected<data.tracks.length)window.Roadbook.selectTrack(data.selected);}catch{}}
$('nav-focus').onclick=()=>{const active=$('nav-stage').classList.toggle('focus');document.body.classList.toggle('map-focus',active);$('nav-focus').textContent=active?'Reducir mapa':'Ampliar mapa';$('nav-focus').setAttribute('aria-pressed',String(active));setTimeout(()=>map.invalidateSize(),50);};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('nav-stage').classList.contains('focus'))$('nav-focus').click();});
$('nav-reset').onclick=()=>{pause();showPreview(0,true);map.setZoom(17);};
$('nav-forget').onclick=()=>{try{localStorage.removeItem('rutas-route');$('nav-local').textContent='Ruta guardada borrada. La ruta actual sigue disponible hasta que cierres la página.';}catch{$('nav-local').textContent='No se pudo acceder al almacenamiento del navegador.';}};

$('nav-stop').onclick=()=>stop();$('nav-focus-stop').onclick=()=>stop();$('nav-fit').onclick=()=>{follow=false;map.fitBounds(layer.getBounds(),{padding:[25,25]});};$('nav-center').onclick=()=>{follow=true;if(position)map.setView(position.getLatLng(),17);else message('Pulsa Iniciar GPS para mostrar tu posición.');};$('nav-progress').oninput=e=>showPreview(route.total*Number(e.target.value)/1000,true);$('nav-next').onclick=()=>showPreview(explore+50,true);$('nav-back').onclick=()=>showPreview(explore-50,true);$('nav-play').onclick=()=>{if(playing){pause();return;}if(explore>=route.total)showPreview(0);$('nav-play').textContent='Pausar';playing=setInterval(()=>{showPreview(explore+Number($("nav-play-speed").value),true);if(explore>=route.total)pause();},500);};$('nav-file').onchange=e=>{window.Roadbook.readFile(e.target.files[0]);e.target.value='';};$('nav-track').onchange=e=>window.Roadbook.selectTrack(Number(e.target.value));window.addEventListener('rutas:route',sync);window.addEventListener('rutas:visible',()=>{sync();setTimeout(()=>map&&map.invalidateSize(),50);});document.addEventListener('visibilitychange',()=>{if(document.hidden){pause();}else if(watch!==null)acquire(session);});window.addEventListener('pagehide',()=>stop(true));restoreLocal();sync();
})();

