(function(){
'use strict';
const $=id=>document.getElementById(id),C=window.RutasNav;
let map,layer,preview,position,accuracy,remaining,route,progress=0,explore=0,watch=null,lock=null,session=0,playing=null,follow=true,lastFix=null,lastVoice=0,lastAlert='',routeRef;
const metres=m=>m<1000?Math.round(m)+' m':(m/1000).toFixed(2).replace('.',',')+' km';
function message(text,warn=false){$('nav-message').textContent=text;$('nav-message').classList.toggle('warn',warn);}
function speak(text){if(!$('nav-voice').checked||!window.speechSynthesis)return;if(text===lastAlert&&Date.now()-lastVoice<30000)return;lastVoice=Date.now();lastAlert=text;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='es-ES';window.speechSynthesis.speak(u);}
function ll(p){return [p.lat,p.lon];}
function init(){if(map)return true;if(!window.L){message('No se pudo cargar el mapa. Recarga la página.',true);return false;}map=L.map('nav-map').setView([40.4,-3.7],6);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).on('tileerror',()=>message('No se pudo cargar parte del mapa. Comprueba tu conexión.',true)).addTo(map);L.control.scale({imperial:false}).addTo(map);map.on('dragstart',()=>{follow=false;});return true;}
function metrics(d){$('nav-done').textContent=metres(d);$('nav-left').textContent=metres(Math.max(0,route.total-d));}
function street(d){const p=C.at(route,d),q=C.at(route,Math.min(route.total,d+30)),h=C.heading(d>=route.total?C.at(route,Math.max(0,d-30)):p,q);$('nav-street').href='https://www.google.com/maps/@?api=1&map_action=pano&viewpoint='+encodeURIComponent(p.lat.toFixed(6)+','+p.lon.toFixed(6))+'&heading='+h.toFixed(0);}
function showPreview(d,pan=false){if(!route)return;explore=Math.max(0,Math.min(route.total,d));const p=C.at(route,explore);preview.setLatLng(ll(p));$('nav-progress').value=route.total?Math.round(explore/route.total*1000):0;$('nav-preview-distance').textContent=metres(explore);street(explore);if(watch===null)metrics(explore);if(pan)map.panTo(ll(p));}
function pause(){if(playing)clearInterval(playing);playing=null;$('nav-play').textContent='Reproducir';}
function controls(active){$('nav-start').disabled=active;$('nav-stop').disabled=!active;['nav-progress','nav-back','nav-next','nav-play'].forEach(id=>$(id).disabled=active);$('nav-mode').textContent=active?'GPS activo':'Vista previa';}
function stop(quiet=false){session++;if(watch!==null)navigator.geolocation.clearWatch(watch);watch=null;lastFix=null;if(lock){lock.release().catch(()=>{});lock=null;}controls(false);if(window.speechSynthesis)window.speechSynthesis.cancel();if(!quiet)message('GPS detenido. Puedes explorar la ruta o continuar desde el punto seleccionado.');}
function sync(){if(!init())return;const data=window.Roadbook.getRoute();if(data.pts===routeRef){map.invalidateSize();return;}stop(true);pause();routeRef=data.pts;route=C.prepare(data.pts);progress=0;explore=0;if(layer)map.removeLayer(layer);if(position){map.removeLayer(position);position=null;}if(accuracy){map.removeLayer(accuracy);accuracy=null;}layer=L.featureGroup().addTo(map);const coords=data.pts.map(ll);L.polyline(coords,{color:'#173d34',weight:7,opacity:.5}).addTo(layer);L.polyline(coords,{color:'#ee641f',weight:4}).addTo(layer);remaining=L.polyline([],{color:'#176dcc',weight:6}).addTo(layer);for(const [p,label,cl] of [[coords[0],'A',''],[coords.at(-1),'B','end']])L.marker(p,{icon:L.divIcon({className:'nav-pin '+cl,html:label,iconSize:[28,28]})}).addTo(layer);preview=L.circleMarker(coords[0],{radius:8,color:'#fff',weight:3,fillColor:'#176dcc',fillOpacity:1}).addTo(layer);map.fitBounds(layer.getBounds(),{padding:[25,25],maxZoom:17});$('nav-name').textContent=(data.sample?'Ejemplo ficticio · carga tu GPX para navegar':'Archivo: '+data.name)+' · '+metres(route.total)+' · '+data.pts.length.toLocaleString('es-ES')+' puntos';$('nav-track').replaceChildren(...data.tracks.map((t,i)=>{const o=document.createElement('option');o.value=i;o.textContent=t.name;o.selected=i===data.selected;return o;}));$('nav-start').disabled=data.sample||route.total<1;message(data.sample?'Vista previa de ejemplo. Carga un GPX real para iniciar el GPS.':'Ruta preparada. Explora las calles o inicia el GPS.');$('nav-speed').textContent='—';$('nav-accuracy').textContent='—';showPreview(0);}
function update(pos,token){if(token!==session||watch===null)return;const c=pos.coords,p={lat:c.latitude,lon:c.longitude};$('nav-accuracy').textContent=Math.round(c.accuracy)+' m';$('nav-speed').textContent=c.speed!==null&&c.speed>=0?Math.round(c.speed*3.6)+' km/h':'—';if(!position){position=L.circleMarker(ll(p),{radius:9,color:'#fff',weight:3,fillColor:'#006dff',fillOpacity:1}).addTo(map);accuracy=L.circle(ll(p),{radius:c.accuracy,color:'#006dff',weight:1,fillOpacity:.08}).addTo(map);}position.setLatLng(ll(p));accuracy.setLatLng(ll(p)).setRadius(c.accuracy);if(follow)map.setView(ll(p),Math.max(map.getZoom(),17),{animate:false});if(c.accuracy>60){message('Señal GPS imprecisa. Esperando una posición más fiable.',true);return;}const elapsed=lastFix?(pos.timestamp-lastFix)/1000:0;const allowance=Math.min(250,Math.max(80,elapsed*45));const m=C.match(route,p,progress,allowance);lastFix=pos.timestamp;if(!m||m.error>Math.max(35,c.accuracy*1.5)){message('Fuera del tramo previsto. Vuelve a la línea; si has cambiado de pasada, para y ajusta el punto de inicio.',true);speak('Te has alejado del recorrido. Comprueba el mapa.');return;}progress=Math.max(progress,m.d);showPreview(progress);metrics(progress);const ahead=[];for(let d=progress;d<Math.min(route.total,progress+160);d+=10)ahead.push(ll(C.at(route,d)));ahead.push(ll(C.at(route,Math.min(route.total,progress+160))));remaining.setLatLngs(ahead);if(route.total-progress<15&&C.distance(p,route.pts.at(-1))<25){stop(true);$('nav-start').disabled=false;message('Has llegado al final del recorrido.');speak('Has llegado al final del recorrido.');return;}message('En ruta · sigue el tramo azul · quedan '+metres(route.total-progress));}
async function acquire(token){if(!navigator.wakeLock||document.hidden)return;try{const l=await navigator.wakeLock.request('screen');if(token===session&&watch!==null)lock=l;else await l.release();}catch{}}
$('nav-start').onclick=()=>{if(!route||watch!==null||window.Roadbook.getRoute().sample)return;if(!navigator.geolocation){message('Este navegador no permite acceder al GPS.',true);return;}pause();progress=explore;follow=true;const token=++session;controls(true);message('Buscando tu posición…');try{watch=navigator.geolocation.watchPosition(p=>update(p,token),e=>{if(token!==session)return;stop(true);message(e.code===1?'Permiso de ubicación denegado. Actívalo en los ajustes del navegador.':'No se pudo obtener el GPS. Puedes volver a intentarlo.',true);},{enableHighAccuracy:true,maximumAge:0,timeout:20000});acquire(token);}catch{stop(true);message('No se pudo iniciar el GPS.',true);}};
$('nav-stop').onclick=()=>stop();$('nav-fit').onclick=()=>{follow=false;map.fitBounds(layer.getBounds(),{padding:[25,25]});};$('nav-center').onclick=()=>{follow=true;if(position)map.setView(position.getLatLng(),17);else message('Pulsa Iniciar GPS para mostrar tu posición.');};$('nav-progress').oninput=e=>showPreview(route.total*Number(e.target.value)/1000,true);$('nav-next').onclick=()=>showPreview(explore+50,true);$('nav-back').onclick=()=>showPreview(explore-50,true);$('nav-play').onclick=()=>{if(playing){pause();return;}if(explore>=route.total)showPreview(0);$('nav-play').textContent='Pausar';playing=setInterval(()=>{showPreview(explore+10,true);if(explore>=route.total)pause();},500);};$('nav-file').onchange=e=>{window.Roadbook.readFile(e.target.files[0]);e.target.value='';};$('nav-track').onchange=e=>window.Roadbook.selectTrack(Number(e.target.value));window.addEventListener('rutas:route',sync);window.addEventListener('rutas:visible',()=>{sync();setTimeout(()=>map&&map.invalidateSize(),50);});document.addEventListener('visibilitychange',()=>{if(document.hidden){pause();}else if(watch!==null)acquire(session);});window.addEventListener('pagehide',()=>stop(true));sync();
})();
