(function(){
'use strict';
const $=id=>document.getElementById(id),A=window.RutasRestrictions,C=window.RutasNav;
let report=null,layer=null,token=0,controller=null,routeRef=null;
const km=m=>(m/1000).toFixed(3).replace('.',',')+' km';
function bounds(pts){let s=90,w=180,n=-90,e=-180;for(const p of pts){s=Math.min(s,p.lat);n=Math.max(n,p.lat);w=Math.min(w,p.lon);e=Math.max(e,p.lon);}return [s-.002,w-.002,n+.002,e+.002];}
function key(pts){return 'rutas-osm-check-v1:'+bounds(pts).join(',');}
function reset(){const state=RutasMap.get();if(!state.route||state.route.pts===routeRef)return;routeRef=state.route.pts;token++;if(controller)controller.abort();report=null;if(layer){state.map.removeLayer(layer);layer=null;}$('road-issues').replaceChildren();$('road-export').disabled=true;$('road-check').disabled=Roadbook.getRoute().sample;$('road-status').textContent=Roadbook.getRoute().sample?'Carga tu GPX real para comprobarlo.':'Sin comprobar. Pulsa Comprobar mi recorrido; se consulta únicamente la zona del mapa.';$('nav-road-alert').hidden=true;try{const cache=JSON.parse(localStorage.getItem(key(routeRef)));if(cache&&Date.now()-cache.saved<86400000)render(cache.data,state.route,true);}catch{}}
function description(issue){return issue.kind==='opposed'?'Posible sentido contrario':issue.kind==='conditional'?'Sentido variable: revisar condiciones':'Coincidencia dudosa entre vías cercanas';}
function link(text,url){const a=document.createElement('a');a.textContent=text;a.href=url;a.target='_blank';a.rel='noopener noreferrer';return a;}
function render(data,route,cached=false){if(data.remark||!Array.isArray(data.elements))throw Error('La consulta de OpenStreetMap está incompleta. No se puede verificar esta ruta.');report=A.analyze(route.pts,data.elements);report.osmDate=data.osm3s?.timestamp_osm_base||null;report.checked=new Date().toISOString();const state=RutasMap.get();if(layer)state.map.removeLayer(layer);layer=L.featureGroup().addTo(state.map);$('road-issues').replaceChildren();for(const [i,issue] of report.issues.entries()){const red=issue.kind==='opposed',symbol=red?'⛔':'⚠',color=red?'#c12719':'#a56800';const popup=document.createElement('div');popup.className='road-popup';const title=document.createElement('b');title.textContent=symbol+' '+description(issue);const detail=document.createElement('p');detail.textContent=issue.name+' · '+km(issue.start)+'–'+km(issue.end)+'. Comprueba la señalización antes de seguir esta traza.';popup.append(title,detail,link('Ver vía y etiquetas en OpenStreetMap','https://www.openstreetmap.org/way/'+issue.way),link('Ver este punto en Street View','https://www.google.com/maps/@?api=1&map_action=pano&viewpoint='+encodeURIComponent(issue.p.lat+','+issue.p.lon)));const marker=L.marker([issue.p.lat,issue.p.lon],{icon:L.divIcon({className:'road-sign',html:symbol,iconSize:[34,34],iconAnchor:[17,17]})}).bindPopup(popup).addTo(layer);L.polyline(C.section(route,issue.start,issue.end).map(p=>[p.lat,p.lon]),{color,weight:8,opacity:.85,dashArray:red?null:'7 6'}).addTo(layer);const li=document.createElement('li'),label=document.createElement('strong'),range=document.createElement('div'),button=document.createElement('button');label.textContent=symbol+' '+issue.name;range.textContent=km(issue.start)+'–'+km(issue.end)+' · '+description(issue);button.type='button';button.className='btn sm';button.textContent='Ver señal '+(i+1);button.onclick=()=>{RutasMap.seek(Math.max(0,issue.start-20));marker.openPopup();};li.append(label,range,button,link('Fuente OSM','https://www.openstreetmap.org/way/'+issue.way));$('road-issues').append(li);}
 const probable=report.issues.filter(i=>i.kind==='opposed').length,doubtful=report.issues.length-probable,date=report.osmDate?new Date(report.osmDate).toLocaleDateString('es-ES'):'no indicada',coverage=report.sampled?Math.round(report.matched/report.sampled*100):0,old=report.osmDate&&Date.now()-Date.parse(report.osmDate)>30*86400000;
 $('road-status').textContent=(report.issues.length?probable+' posibles tramos en sentido contrario y '+doubtful+' puntos dudosos.':'No se detectaron conflictos de sentido único con estos datos. Esto no confirma que toda la ruta sea legal.')+' Coincidencia geométrica en el '+coverage+' % de las muestras. Fecha de los datos OSM: '+date+(old?' (más de 30 días; requiere verificación actual).':'.')+(cached?' Datos recuperados del dispositivo.':'');$('road-export').disabled=false;alertAt(state.progress);RutasMap.refresh();window.dispatchEvent(new CustomEvent("rutas:roads",{detail:{pts:route.pts,elements:data.elements}}));}
async function check(){const state=RutasMap.get();if(!state.route||Roadbook.getRoute().sample)return;const own=++token,route=state.route,box=bounds(route.pts),width=C.distance({lat:box[0],lon:box[1]},{lat:box[0],lon:box[3]}),height=C.distance({lat:box[0],lon:box[1]},{lat:box[2],lon:box[1]});if(width*height>250000000){$('road-status').textContent='La zona es demasiado extensa para esta consulta. Selecciona un segmento más corto.';return;}$('road-check').disabled=true;$('road-status').textContent='Consultando sentidos de circulación en OpenStreetMap…';const requestController=new AbortController();controller=requestController;const timer=setTimeout(()=>requestController.abort(),45000);try{const query='[out:json][timeout:30];way["highway"]('+box.join(',')+');out tags geom;',response=await fetch('https://overpass.kumi.systems/api/interpreter?data='+encodeURIComponent(query),{signal:requestController.signal});if(!response.ok)throw Error('Servidor del mapa no disponible ('+response.status+'). Inténtalo más tarde.');const data=await response.json();if(own!==token)return;render(data,route);try{localStorage.setItem(key(route.pts),JSON.stringify({saved:Date.now(),data}));}catch{}}catch(err){if(own===token)$('road-status').textContent='No se ha podido completar la comprobación. '+(err.name==='AbortError'?'El servidor ha tardado demasiado.':err.message);}finally{clearTimeout(timer);if(own===token){$('road-check').disabled=false;controller=null;}}}
function upcoming(d){return report?.issues.find(i=>i.end+10>=d&&i.start-d<=100);}
function alertAt(d){const issue=upcoming(d);$('nav-road-alert').hidden=!issue;if(issue)$('nav-road-alert').textContent=(issue.kind==='opposed'?'⛔ Posible sentido contrario':'⚠ Sentido por comprobar')+' · '+issue.name+(issue.start>d?' · en '+Math.round(issue.start-d)+' m':'')+'. No sigas esta traza sin comprobar la señalización.';}
window.RutasChecks={gpsAlert:d=>{const i=upcoming(d);return i?(i.kind==='opposed'?'Atención, posible sentido contrario. ':'Atención, sentido de circulación por comprobar. ')+i.name+'. Revisa la señalización antes de continuar.':null;}};
$('road-data').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;const state=RutasMap.get();if(!state.route||Roadbook.getRoute().sample){$('road-status').textContent='Carga primero tu GPX.';return;}if(file.size>15000000){$('road-status').textContent='El archivo de calles es demasiado grande (máximo 15 MB).';return;}const own=++token;if(controller)controller.abort();try{const data=JSON.parse(await file.text());if(own!==token)return;if(!Array.isArray(data.elements)||!data.elements.every(w=>w.type==='way'&&Number.isSafeInteger(w.id)&&Array.isArray(w.geometry)&&w.geometry.every(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lon)&&Math.abs(p.lat)<=90&&Math.abs(p.lon)<=180)))throw Error('No es un archivo de calles compatible.');render(data,state.route);try{localStorage.setItem(key(state.route.pts),JSON.stringify({saved:Date.now(),data}));}catch{}}catch(err){if(own===token)$('road-status').textContent='No se pudo leer el archivo: '+err.message;}finally{if(own===token)$('road-check').disabled=false;}};
$('road-check').onclick=check;$('road-export').onclick=()=>{if(!report)return;const quote=s=>'"'+String(s??'').replace(/"/g,'""')+'"';const rows=[['calle','km_inicio','km_fin','resultado','via_osm','fecha_datos_osm']].concat(report.issues.map(i=>[i.name,(i.start/1000).toFixed(3),(i.end/1000).toFixed(3),description(i),'https://www.openstreetmap.org/way/'+i.way,report.osmDate]));const blob=new Blob(['\uFEFF'+rows.map(r=>r.map(quote).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='revision-sentidos.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);};window.addEventListener('rutas:check-route',reset);window.addEventListener('rutas:progress',e=>alertAt(e.detail.distance));reset();
})();
