(function(root){
'use strict';
const R=6371000,MAX=20000;
function valid(p){return !!p&&Number.isFinite(Number(p.lat))&&Number.isFinite(Number(p.lon))&&Math.abs(Number(p.lat))<=90&&Math.abs(Number(p.lon))<=180;}
function distance(a,b){if(!valid(a)||!valid(b))return 0;const r=Math.PI/180,p1=Number(a.lat)*r,p2=Number(b.lat)*r,dp=(Number(b.lat)-Number(a.lat))*r,dl=(Number(b.lon)-Number(a.lon))*r,x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));}
function clean(p){if(!valid(p))return null;const raw=Number(p.time),parsed=Number.isFinite(raw)?raw:Date.parse(p.time),stamp=Number.isFinite(parsed)?parsed:Date.now();const out={lat:Number(p.lat),lon:Number(p.lon),time:new Date(stamp).toISOString()};for(const k of ['ele','accuracy','speed','error','progress'])if(Number.isFinite(Number(p[k])))out[k]=Number(p[k]);out.onRoute=p.onRoute!==false;return out;}
function append(list,point,opts){const out=Array.isArray(list)?list:[],p=clean(point);if(!p||Number(p.accuracy)>100)return false;const o=opts||{},last=out.at(-1),gap=last?distance(last,p):Infinity,elapsed=last?Date.parse(p.time)-Date.parse(last.time):Infinity;if(last&&gap<(o.minMetres||4)&&elapsed<(o.minMillis||10000)){last.time=p.time;last.accuracy=p.accuracy;last.speed=p.speed;last.error=p.error;last.progress=p.progress;last.onRoute=p.onRoute;return false;}out.push(p);if(out.length>(o.max||MAX))out.splice(0,out.length-(o.max||MAX));return true;}
function stamp(v){const n=Number(v);return Number.isFinite(n)?n:Date.parse(v);}
function summary(list){const pts=(Array.isArray(list)?list:[]).filter(valid);let metres=0,off=0,maxError=0;for(let i=0;i<pts.length;i++){if(i)metres+=distance(pts[i-1],pts[i]);if(pts[i].onRoute===false)off++;if(Number.isFinite(pts[i].error))maxError=Math.max(maxError,pts[i].error);}const first=pts[0],last=pts.at(-1),elapsed=first&&last?stamp(last.time)-stamp(first.time):0,seconds=Number.isFinite(elapsed)?Math.max(0,elapsed/1000):0;return {points:pts.length,metres,seconds,offRoute:off,maxError,started:first?.time||null,ended:last?.time||null};}
function esc(v){const s=String(v??'');return /[;"\n\r]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s;}
function csv(info){const d=info||{},s=d.track||summary(d.points),rows=[['Campo','Valor'],['Ruta',d.name||'Recorrido'],['Distancia prevista (m)',Math.round(Number(d.total)||0)],['Distancia realizada (m)',Math.round(s.metres||0)],['Duración realizada (s)',Math.round(s.seconds||0)],['Puntos GPS',s.points||0],['Posiciones fuera de ruta',s.offRoute||0],['Desvío máximo (m)',Math.round(s.maxError||0)],['Tramos pendientes',d.missing||'Ninguno'],['Inicio',s.started||''],['Final',s.ended||'']];return '\ufeff'+rows.map(r=>r.map(esc).join(';')).join('\r\n')+'\r\n';}
function filename(name,ext){const n=String(name||'recorrido').replace(/\.gpx$/i,'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^A-Za-z0-9._-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,60)||'recorrido';return n+'-realizado.'+(ext||'gpx');}
const api={valid,distance,clean,append,summary,csv,filename,MAX};if(typeof module==='object'&&module.exports)module.exports=api;else root.RutasViajeCore=api;
})(typeof globalThis!=='undefined'?globalThis:this);
