const test=require('node:test'),assert=require('node:assert/strict'),A=require('../restrictions-core');
const line=[{lat:41,lon:2},{lat:41.002,lon:2}],way=(tags,geometry=line,id=1)=>({type:'way',id,tags:{highway:'residential',...tags},geometry});
test('sentido permitido y contrario yes',()=>{assert.equal(A.analyze(line,[way({oneway:'yes'})]).issues.length,0);assert.equal(A.analyze(line.slice().reverse(),[way({oneway:'yes'})]).issues[0].kind,'opposed');});
test('oneway inverso y excepción para motor',()=>{assert.equal(A.analyze(line,[way({oneway:'-1'})]).issues[0].kind,'opposed');assert.equal(A.analyze(line.slice().reverse(),[way({oneway:'-1'})]).issues.length,0);assert.equal(A.rule({oneway:'yes','oneway:motor_vehicle':'no'}).direction,0);});
test('doble sentido y ausencia de etiqueta no generan infracción',()=>{for(const tags of [{oneway:'no'},{}])assert.equal(A.analyze(line.slice().reverse(),[way(tags)]).issues.length,0);});
test('rotonda implícita y restricción horaria',()=>{assert.equal(A.rule({junction:'roundabout'}).direction,1);assert.equal(A.analyze(line,[way({'oneway:conditional':'yes @ (08:00-18:00)'})]).issues[0].kind,'conditional');});
test('vía paralela cercana rebaja a coincidencia dudosa',()=>{const parallel=line.map(p=>({...p,lon:p.lon+.000025}));assert.equal(A.analyze(line.slice().reverse(),[way({oneway:'yes'}),way({oneway:'no'},parallel,2)]).issues[0].kind,'ambiguous');});
test('una vía lejana no se asigna a la ruta',()=>{assert.equal(A.analyze(line.slice().reverse(),[way({oneway:'yes'},line.map(p=>({...p,lon:p.lon+.001})))]).issues.length,0);});
test('las unidades de OSM se interpretan en metros y toneladas',()=>{assert.equal(A.metresOf('3.5'),3.5);assert.equal(A.metresOf('3,5 m'),3.5);assert.equal(A.metresOf(`12'6"`),3.81);assert.equal(A.tonnesOf('7.5 t'),7.5);assert.equal(A.tonnesOf('3500 kg'),3.5);
 for(const v of [null,'','default','none','unsigned','no sé'])assert.equal(A.metresOf(v),null);});
test('un limite solo salta si el vehiculo no cabe',()=>{const tags={highway:'residential',maxheight:'3.5'};
 assert.equal(A.vehicle(tags,{height:4.1}).length,1);
 assert.equal(A.vehicle(tags,{height:3.2}).length,0);
 assert.equal(A.vehicle(tags,{}).length,0);
 assert.equal(A.vehicle(tags,null).length,0);
 assert.equal(A.vehicle(tags,{height:4.1})[0].kind,'height');});
test('el limite especifico de camion manda sobre el general',()=>{assert.equal(A.vehicle({maxweight:'12','maxweight:hgv':'7.5'},{weight:10}).length,1);
 assert.equal(A.vehicle({maxweight:'12','maxweight:hgv':'7.5'},{weight:10})[0].kind,'weight');
 assert.equal(A.vehicle({maxweight:'12'},{weight:10}).length,0);});
test('prohibiciones de acceso y limites variables',()=>{assert.equal(A.vehicle({hgv:'no'},{})[0].kind,'access');
 assert.equal(A.vehicle({access:'private'},{})[0].kind,'access');
 assert.equal(A.vehicle({access:'destination'},{}).length,0);
 assert.equal(A.vehicle({'maxweight:conditional':'5 @ (Mo-Fr 08:00-20:00)'},{})[0].kind,'limit-variable');});
test('un puente bajo en la ruta se comunica con su medida',()=>{const bridge=[];for(let i=0;i<12;i++)bridge.push({lat:41+i*0.00018,lon:2});
 const r=A.analyze(bridge,[way({maxheight:'3.2',name:'Pont Vell'},bridge)],{height:3.9});
 assert.equal(r.issues.length,1);assert.equal(r.issues[0].kind,'height');
 assert(r.issues[0].detail.includes('3.2'));assert(r.issues[0].detail.includes('3.9'));
 assert.equal(A.analyze(bridge,[way({maxheight:'3.2',name:'Pont Vell'},bridge)],{height:3.0}).issues.length,0);});
test('sentido contrario y limite de peso se comunican por separado',()=>{const line2=[];for(let i=0;i<12;i++)line2.push({lat:41+i*0.00018,lon:2});
 const r=A.analyze(line2.slice().reverse(),[way({oneway:'yes',maxweight:'5',name:'Carrer Estret'},line2)],{weight:9});
 assert.deepEqual(r.issues.map(i=>i.kind).sort(),['opposed','weight']);});
test('contexto de calle distingue curva sin modificar coordenadas',()=>{const N=require('../nav-core'),pts=[{lat:41,lon:2},{lat:41.002,lon:2},{lat:41.002,lon:2.002}],r=N.prepare(pts),before=JSON.stringify(pts),turns=N.turns(r),out=A.enrichTurns(r,turns,[way({name:'Calle de prueba'},pts)]);assert(out.some(t=>t.label==='Curva a la derecha'&&t.toRoad==='Calle de prueba'));assert.equal(JSON.stringify(pts),before);});
